
name: ServeRest Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Subir ServeRest
        run: npx serverest &

      - name: Aguardar ServeRest Inicializar
        run: sleep 5

      - name: Criar Pasta de Relatório
        run: mkdir -p Reports

      - name: Executar testes
        run: |
          npx newman run "Collections/ServeRestAPI.postman_collection.json" \
            -e "Environments/ServeRest-localhost.postman_environment.json" \
            -r htmlextra \
            --reporter-htmlextra-export "Reports/report.html" \
            --suppress-exit-code

      - name: Relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: Reports/report.html 